"use strict";
define(['model'],function($model){
	
	var model = new $model({"meta":{"message":"List of Master Configs","limit":10,"next":null,"prev":null,"last":1,"count":9,"page":1,"pages":1,"epoch":1594889745,"code":200},"data":null});
	var data = [{"SCHOOL_NAME":"PROTOTYPE","SCHOOL_ALIAS":"DU","SCHOOL_LOGO":"logo.jpg","SCHOOL_ADDRESS":"STO.TOMAS BATANGAS","START_SY":2013,"ACTIVE_SY":2019,"DEFAULT_":{"PRECISION":0,"FLOOR_GRADE":70,"CEIL_GRADE":100,"PERIOD":{"id":3,"key":"THRDGRDG","alias":{"short":"MID","full":"Midterm"}},"SEMESTER":{"id":45,"key":"SCNDSEMS","alias":{"short":"2st","full":"Second Sem"}}},"SCHOOL_ID":"DU","ACTIVE_DEPT":"SH","SCHOOL_YEARS":[{"id":2013,"label":"2013-2014","code":13},{"id":2014,"label":"2014-2015","code":14},{"id":2015,"label":"2015-2016","code":15},{"id":2016,"label":"2016-2017","code":16},{"id":2017,"label":"2017-2018","code":17},{"id":2018,"label":"2018-2019","code":18},{"id":2019,"label":"2019-2020","code":19}],"PERIODS":[{"id":1,"name":"Midterm First Sem","alias":{"short":"MID","full":"Midterm"},"key":"FRSTGRDG"},{"id":2,"name":"Finals First Sem","alias":{"short":"FIN","full":"Finals"},"key":"SCNDGRDG"},{"id":3,"name":"Midterm Second Sem","alias":{"short":"MID","full":"Midterm"},"key":"THRDGRDG"},{"id":4,"name":"Finals Second Sem","alias":{"short":"FIN","full":"Finals"},"key":"FRTHGRDG"}],"SEMESTERS":[{"id":25,"name":"First Semester","alias":{"short":"1st","full":"First Sem"},"key":"FRSTSEMS"},{"id":45,"name":"Second Semester","alias":{"short":"2nd","full":"Second Sem"},"key":"SCNDSEMS"}],"DEPARTMENTS":{"HS":"H.School","SH":"S.High","PS":"P.School","GS":"G.School"},"YEAR_LEVELS":[{"id":"G7","name":"Gr 7","alias":"G7","department_id":"HS"},{"id":"GY","name":"Gr 11","alias":"G11","department_id":"SH"},{"id":"NU","name":"N","alias":"N","department_id":"PS"},{"id":"G1","name":"Gr 1","alias":"G1","department_id":"GS"},{"id":"G8","name":"Gr 8","alias":"G8","department_id":"HS"},{"id":"GZ","name":"Gr 12","alias":"G12","department_id":"SH"},{"id":"K1","name":"K I","alias":"K1","department_id":"PS"},{"id":"G2","name":"Gr 2","alias":"G2","department_id":"GS"},{"id":"G9","name":"Gr 9","alias":"G9","department_id":"HS"},{"id":"K2","name":"K II","alias":"K2","department_id":"PS"},{"id":"G3","name":"Gr 3","alias":"G3","department_id":"GS"},{"id":"GX","name":"Gr 10","alias":"G10","department_id":"HS"},{"id":"G4","name":"Gr 4","alias":"G4","department_id":"GS"},{"id":"G5","name":"Gr 5","alias":"G5","department_id":"GS"},{"id":"G6","name":"Gr 6","alias":"G5","department_id":"GS"}],"PROGRAMS":{"REGLR":"Regular","SCIEN":"Science","PILOT":"Pilot","SHABM":"ABM","STEMR":"STEM","SHGAS":"GAS","SHHUM":"HUMSS","MIXED":"Mixed"}}];
	model.data = data;
	model.GET = function(){
			return {success:{meta:{},data:model.data[0]}};
		}
	return model;
});